### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by vezaynk** [sharetribe/ftw-hourly#219]
This repo (along with ftw-daily, and ftw-product) are excellent starting points for sharetribe apps.

However, I believe that it is critical to add TypeScript support to it, as without it it is much harder to navigate the codebase.

Would you consider investing time into making it strong typed?

**Comment by Gnito** [comment]
Hi!

At the moment, we are not planning to go in this direction. The number of people, who are familiar with JavaScript, is still quite much bigger. Furthermore, based on the level of support questions, Flex seems to gain attention also from people who have some background/exposure to JS from different web projects (WordPress, Rails, etc.) - but who are not full-time front-end devs.

TypeScript would also be a barrier for existing marketplaces to follow new updates and features - the template also works as a guide on how to take new features into use in their own codebase. In addition, as you can imagine, such a rewrite would also be a pretty heavy task to accomplish. 

As a summary of all this, it's not easy to justify and prioritize this work against other feature requests in the backlog. However, TypeScript has had pretty strong growth in recent years and especially among frontend-focused consultancy companies. So, we do keep an eye on this and it's not completely out of the picture that we'd start adapting it at some point.

Btw. community-build client apps are more than welcome! ...and if you represent an expert partner (or consider to be one) - creating your own template might be a good idea if they make your team faster at creating new marketplaces. I.e. some have specialized in different languages (js/ts/clj/etc.) or frameworks like Vue and Angular.

Regarding this line of thought, we have learned that supporting several different templates is quite a burden, even if their codebases are close to each other. As a consequence, we are currently working to create a combined template. Basically, this means that we combine the features of FTW-daily, FTW-hourly, and FTW-product into a single template. After the combined template is released, it might become more interesting to build community-driven templates - since one template could support more marketplace types.

> Side note: navigating the codebase should be possible with modern code editors (I think most editors know how to follow relative module imports), but I assume that you talk about avoiding type errors, which naturally is a pretty nonexistent issue with strongly typed languages.

**Comment by knyzorg** [comment]
> The number of people, who are familiar with JavaScript, is still quite much bigger.

It will always be this way. TypeScript is a superset of JavaScript, but anyone who understands JS will easily understand TS. It's literally just adding type-hints.

> TypeScript would also be a barrier for existing marketplaces to follow new updates and features

This is true. How common is it for projects to pull updates from these repositories? I would expect most people to take the latest version at the time, and stick with it.

> Regarding this line of thought, we have learned that supporting several different templates is quite a burden, even if their codebases are close to each other.

Very understandable. I was quite surprised at the fact that you maintain three different starter templates. If I were you, I'd kill off 2 of them and invest heavily in the last (not suggesting it, just saying what I personally would've done).

Do you have the consolidate template published somewhere? I understand its a WIP. Would be 10/10 if you could do it in TS from the get-go.

Looking at the types of components in my main way of understanding how frameworks fit together, before even running them. 

I would be willing to personally contribute to the effort if it's a direction you want to go in.

**Comment by Gnito** [comment]
Indeed, the combined template is still a work in progress. I can't say yet when it will be published, but it is a JavaScript template relying quite much on existing templates and code in them. Most of the work is done - and as a consequence, we are not embracing TS at this point.

We are currently making quite big changes to the Flex service and APIs. That effort is likely to take the whole next year and we are not planning to divert the focus on changing the language of the client app. Honestly, I think that if we start supporting TS at some point in the future, we probably start by creating a separate component library first. ...and after that consider again if we want to create a separate TS template.

So, thank you for your willingness to contribute to creating a TS template, but we are not ready to go in that direction with the in-house templates at this point.

**Comment by Gnito** [comment]
Closing this for now as we are not planning to add typescript support anytime soon.
